version: "3.6"

services:
  prometheus:
    container_name: xebicon-prometheus
    image: pgdejardin/xebicon-prometheus:latest
    ports:
    - "9090:9090"
    networks:
    - xebicon
  grafana:
    container_name: xebicon-grafana
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - xebicon
  myApp:
    container_name: xebicon-nodejs
    image: pgdejardin/xebicon-node-prometheus:latest
    ports:
      - "8080:8080"
    networks:
      - xebicon
  cadvisor:
    container_name: xebicon-cadvisor
    image: google/cadvisor:latest
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    depends_on:
      - redis
    ports:
      - 8081:8080
    networks:
      - xebicon
  redis:
    image: redis:alpine
    container_name: xebicon-redis
    ports:
      - 6379:6379
    networks:
      - xebicon

networks:
  xebicon:
    driver: bridge
